### PR TITLE
Add ToggleActions to booleanReducer

### PR DESCRIPTION
**Pull request by darthtrevino**
Hello @try-again-apps - I almost just started a project like this because I find myself writing similar reducers all the time. I have some ideas for other reducer patterns that would make sense - I'll cut some issues to capture those ideas.

* Update the reducer creators so that they take a config object as the first parameter and the initial state as the second parameter. This will allow for more flexible configuration per reducer without introducing breaking library changes.
* Add yarn.lock

### CODE REVIEW

**Review by try-again-apps — CHANGES_REQUESTED** [review]
Great improvement :) Just one thing - please roll back to single quote usage (I'd rather use double quotes when needed) and please check if lint passes because we got build break: https://travis-ci.org/try-again-apps/redux-common-reducers/jobs/351487829 - then I'll merge it to master :), update docs and publish new version. Thanks :)

**Review by try-again-apps — CHANGES_REQUESTED** [review]
Almost great - thanks a lot - but one more thing - please do not use tabs  two spaces are enough for js. Could you please change back that last one thing?

**Comment by darthtrevino** [comment]
Sure - to be clear tabs aren't "more space", it's just a configurable mark. But two-spaces is pretty normal convention.

**Comment by try-again-apps** [comment]
Just wanted to say sorry for being absent and not reacting on changes you've made.
Really didin't have time for this - a lot of is happening these days. Never mind.
Anyway I've analysed again the changes and decided not to add them. I've tried those changes in action and the new API generates a lot of additional code - because now instead of calling function with parameters we need to create new object with key => value where keys like 'trueActions', 'changeActions' makes big reducers even bigger.
So far the API is pretty simple and works well - I know API is not "breaking change proof" but it is prety simple and lets reducers to be small.

**Pull request closed without merging**
